### ISSUE TITLE
SunInWindow always true after update

### ISSUE THREAD

**Issue by jonferreira** [alisdairjsmyth/node-red-contrib-blindcontroller#9]
Hi,

Something well weird happened today after updating from 3.2.0
First of all it appears you've removed sunpos which means it now needs to be installed manually - no biggy.
Even though it's installed though I'm seeing this when staring node-red

 6 Jan 14:17:08 - [warn] Missing node modules:
 6 Jan 14:17:08 - [warn]  - node-red-contrib-blindcontroller: sunpos
 6 Jan 14:17:08 - [info] Removing modules from config

And all windows are behaving as sun was in window. You can see an example bellow

{ "topic": "blind", "payload": { "channel": "190", "mode": "Winter", "orientation": 80, "noffset": "70", "poffset": "70", "top": 210, "bottom": 0, "depth": 999, "altitudethreshold": 0, "increment": 5, "maxopen": "15", "maxclosed": "50", "temperaturethreshold": "30", "cloudsthreshold": "0.5", "nightposition": "100", "expiryperiod": 2, "blindPosition": "15", "sunInWindow": true, "blindPositionReasonCode": "05", "blindPositionReasonDesc": "Sun in window" }, "_msgid": "848f0370.7b71", "location": { "lat": "39.40975", "lon": "-9.12617" }, "time": "2017-01-06T14:32:09.422Z", "data": { "channel": "190", "altitude": 23.08581696330184, "azimuth": 207.41053751519533, "blindPosition": "15" } }

Orientation is 80 with negative/positive offset of 70 so sun is in window from (80-70)10 to (80+70)160. Given that azimuth is 207 clearly sun is *not* in window

Any idea what's going on?

**Comment by alisdairjsmyth** [comment]
Fix available in 4.2.2

The sunpos node was being maintained in two locations [node-red-contrib-sunpos](https://www.npmjs.com/package/node-red-contrib-sunpos) and node-red-contrib-blindcontroller, which didn't make sense.  As such I decided to remove it from this repository, which was the reason for the major version change v3 -> v4.

Delete the existing node from your flow, install node-red-contrib-sunpos and re-introduce.

**Comment by jonferreira** [comment]
OK thanks, the update does fix the sun in window.
on the other hand I still have that warning when starting node-red and can't figure out why!

**Comment by alisdairjsmyth** [comment]
Have you replaced the node in your flow with the equivalent from node-red-contrib-sunpos?

**Comment by jonferreira** [comment]
sure, I've deleted all sunpos "old" nodes and re-added after installing node-red-contrib-sunpos
